### ISSUE TITLE
Servo doing nothing when using DrivePercentage with a value of 0.00

### ISSUE THREAD

**Issue by AlexanderPilhar** [TheBekker/Bekker.Adafruit.PCA9685PwmDriver#1]
I was testing this library with the given example code and encountered some effect I'm not sure of if this is intended to be that way:

When using Method `DrivePercentage()` with a percentage-value of 0.00 the servo doesn't do anything.

So, I had a look at the code and saw that the Method `Map()` is mapping the percentage-value to a pulse-value somewhere between `MinPulse` and `MaxPulse`. But then right afterwards the percentage-value gets checked if it equals 0 and if true the pulse-value gets set to 0. This means that the minimum percentage-value passed to `DrivePercentage()` is 0.01 - is this intended to be that way?

Here's the code snippet:
```
var intPercentage = (int)(percentage*100);
var pulse = Map(intPercentage, 0, 100, MinPulse, MaxPulse);
if (intPercentage == 0)
{
    pulse = 0;
}
```

Also, in the given example percentage-values of 0 and 100 are being used, when they should be 0.00 and 1.00 I think (or rather 0.01 and 1.00).

**Comment by TheBekker** [comment]
Hi Alexander

Its been a while since i worked on this, or even used it (i might get back to it soon tough)
I actually think that this was intended, since i never wrote it for controlling servo's, but actually for controlling motor controllers with the pwm signal.

So DrivePercentage with value 0.0, should stop the motors.

I would love to take a look and make it more compatible with actual servo's, and you are very welcome to do a PR.

I might actually do a rewrite, since theres more official support for PWM and the PCA9685 now:
https://github.com/ms-iot/BusProviders/tree/develop/PWM

**Comment by AlexanderPilhar** [comment]
I see - this makes sense, obviously!

There also is a library by Adafruit ([Adafruit Class Library for Windows IoT Core](https://learn.adafruit.com/adafruit-class-library-for-windows-iot-core/overview?view=all#pca9685-class)) and they do handle 0 the same way.

I'll be happy to do so, just let me know once you are done with adaption for servo motors!

So, with regards to controlling motor controllers, this issue can be closed, I guess.
